apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: friday-txt
spec:
  rules:
  - host: ascii.friday.horse
    http:
      paths:
      - backend:
          serviceName: horse-txt
          servicePort: 80
        path: /
  - host: txt.friday.horse
    http:
      paths:
      - backend:
          serviceName: horse-txt
          servicePort: 80
        path: /
  tls:
  - hosts:
    - ascii.friday.horse
    - txt.friday.horse
    secretName: friday-txt-tls
